// Generated by `supabase gen typescript-types`. Do not edit by hand — re-run
// via `mcp__supabase__generate_typescript_types` whenever the schema changes.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.5";
  };
  public: {
    Tables: {
      afiliados: {
        Row: {
          codigo: string;
          created_at: string;
          datos_pago: Json | null;
          email: string | null;
          estatus: Database["public"]["Enums"]["afiliado_estatus"];
          id: string;
          nombre: string;
          updated_at: string;
          whatsapp: string | null;
        };
        Insert: {
          codigo: string;
          created_at?: string;
          datos_pago?: Json | null;
          email?: string | null;
          estatus?: Database["public"]["Enums"]["afiliado_estatus"];
          id?: string;
          nombre: string;
          updated_at?: string;
          whatsapp?: string | null;
        };
        Update: {
          codigo?: string;
          created_at?: string;
          datos_pago?: Json | null;
          email?: string | null;
          estatus?: Database["public"]["Enums"]["afiliado_estatus"];
          id?: string;
          nombre?: string;
          updated_at?: string;
          whatsapp?: string | null;
        };
        Relationships: [];
      };
      clientes: {
        Row: {
          afiliado_id: string | null;
          created_at: string;
          email: string | null;
          estatus: Database["public"]["Enums"]["cliente_estatus"];
          fecha_compra: string | null;
          id: string;
          inmobiliaria: string | null;
          nombre: string;
          notas: string | null;
          origen: Database["public"]["Enums"]["cliente_origen"];
          updated_at: string;
          user_id: string | null;
          whatsapp: string | null;
        };
        Insert: {
          afiliado_id?: string | null;
          created_at?: string;
          email?: string | null;
          estatus?: Database["public"]["Enums"]["cliente_estatus"];
          fecha_compra?: string | null;
          id?: string;
          inmobiliaria?: string | null;
          nombre: string;
          notas?: string | null;
          origen?: Database["public"]["Enums"]["cliente_origen"];
          updated_at?: string;
          user_id?: string | null;
          whatsapp?: string | null;
        };
        Update: {
          afiliado_id?: string | null;
          created_at?: string;
          email?: string | null;
          estatus?: Database["public"]["Enums"]["cliente_estatus"];
          fecha_compra?: string | null;
          id?: string;
          inmobiliaria?: string | null;
          nombre?: string;
          notas?: string | null;
          origen?: Database["public"]["Enums"]["cliente_origen"];
          updated_at?: string;
          user_id?: string | null;
          whatsapp?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "clientes_afiliado_id_fkey";
            columns: ["afiliado_id"];
            isOneToOne: false;
            referencedRelation: "afiliados";
            referencedColumns: ["id"];
          },
        ];
      };
      comisiones: {
        Row: {
          afiliado_id: string;
          base_mxn: number;
          cliente_id: string;
          created_at: string;
          estatus: Database["public"]["Enums"]["comision_estatus"];
          fecha_devengo: string;
          fecha_pago: string | null;
          id: string;
          monto_mxn: number;
          pago_id: string;
          porcentaje: number;
          referencia_pago: string | null;
          tipo: Database["public"]["Enums"]["comision_tipo"];
          updated_at: string;
        };
        Insert: {
          afiliado_id: string;
          base_mxn: number;
          cliente_id: string;
          created_at?: string;
          estatus?: Database["public"]["Enums"]["comision_estatus"];
          fecha_devengo?: string;
          fecha_pago?: string | null;
          id?: string;
          monto_mxn: number;
          pago_id: string;
          porcentaje: number;
          referencia_pago?: string | null;
          tipo: Database["public"]["Enums"]["comision_tipo"];
          updated_at?: string;
        };
        Update: {
          afiliado_id?: string;
          base_mxn?: number;
          cliente_id?: string;
          created_at?: string;
          estatus?: Database["public"]["Enums"]["comision_estatus"];
          fecha_devengo?: string;
          fecha_pago?: string | null;
          id?: string;
          monto_mxn?: number;
          pago_id?: string;
          porcentaje?: number;
          referencia_pago?: string | null;
          tipo?: Database["public"]["Enums"]["comision_tipo"];
          updated_at?: string;
        };
        Relationships: [];
      };
      pagos: {
        Row: {
          cliente_id: string;
          concepto: Database["public"]["Enums"]["pago_concepto"];
          created_at: string;
          fecha: string;
          id: string;
          metodo: string | null;
          monto_mxn: number;
          referencia: string | null;
          suscripcion_id: string | null;
        };
        Insert: {
          cliente_id: string;
          concepto: Database["public"]["Enums"]["pago_concepto"];
          created_at?: string;
          fecha?: string;
          id?: string;
          metodo?: string | null;
          monto_mxn: number;
          referencia?: string | null;
          suscripcion_id?: string | null;
        };
        Update: {
          cliente_id?: string;
          concepto?: Database["public"]["Enums"]["pago_concepto"];
          created_at?: string;
          fecha?: string;
          id?: string;
          metodo?: string | null;
          monto_mxn?: number;
          referencia?: string | null;
          suscripcion_id?: string | null;
        };
        Relationships: [];
      };
      sitios: {
        Row: {
          cliente_id: string;
          config: Json;
          created_at: string;
          dominio_custom: string | null;
          estado_dns: Database["public"]["Enums"]["sitio_estado_dns"];
          estatus: Database["public"]["Enums"]["sitio_estatus"];
          id: string;
          netlify_site_id: string | null;
          subdominio: string | null;
          ultimo_deploy_at: string | null;
          updated_at: string;
        };
        Insert: {
          cliente_id: string;
          config?: Json;
          created_at?: string;
          dominio_custom?: string | null;
          estado_dns?: Database["public"]["Enums"]["sitio_estado_dns"];
          estatus?: Database["public"]["Enums"]["sitio_estatus"];
          id?: string;
          netlify_site_id?: string | null;
          subdominio?: string | null;
          ultimo_deploy_at?: string | null;
          updated_at?: string;
        };
        Update: {
          cliente_id?: string;
          config?: Json;
          created_at?: string;
          dominio_custom?: string | null;
          estado_dns?: Database["public"]["Enums"]["sitio_estado_dns"];
          estatus?: Database["public"]["Enums"]["sitio_estatus"];
          id?: string;
          netlify_site_id?: string | null;
          subdominio?: string | null;
          ultimo_deploy_at?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      user_roles: {
        Row: {
          created_at: string;
          role: Database["public"]["Enums"]["user_role"];
          user_id: string;
        };
        Insert: {
          created_at?: string;
          role?: Database["public"]["Enums"]["user_role"];
          user_id: string;
        };
        Update: {
          created_at?: string;
          role?: Database["public"]["Enums"]["user_role"];
          user_id?: string;
        };
        Relationships: [];
      };
      suscripciones: {
        Row: {
          cliente_id: string;
          created_at: string;
          dia_cobro: number;
          estatus: Database["public"]["Enums"]["suscripcion_estatus"];
          fecha_cancelacion: string | null;
          fecha_inicio: string;
          id: string;
          monto_mxn: number;
          updated_at: string;
        };
        Insert: {
          cliente_id: string;
          created_at?: string;
          dia_cobro: number;
          estatus?: Database["public"]["Enums"]["suscripcion_estatus"];
          fecha_cancelacion?: string | null;
          fecha_inicio: string;
          id?: string;
          monto_mxn: number;
          updated_at?: string;
        };
        Update: {
          cliente_id?: string;
          created_at?: string;
          dia_cobro?: number;
          estatus?: Database["public"]["Enums"]["suscripcion_estatus"];
          fecha_cancelacion?: string | null;
          fecha_inicio?: string;
          id?: string;
          monto_mxn?: number;
          updated_at?: string;
        };
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: {
      current_user_cliente_id: { Args: Record<string, never>; Returns: string };
      current_user_is_operator: { Args: Record<string, never>; Returns: boolean };
      invite_broker: {
        Args: { p_cliente_id: string; p_email: string; p_password: string };
        Returns: string;
      };
    };
    Enums: {
      afiliado_estatus: "activo" | "pausado" | "baja";
      cliente_estatus:
        | "prospecto"
        | "pagado"
        | "generado"
        | "desplegado"
        | "entregado"
        | "activo"
        | "cancelado";
      cliente_origen: "meta_ads" | "afiliado" | "directo" | "referido";
      comision_estatus: "devengada" | "por_pagar" | "pagada";
      comision_tipo: "frontend_30" | "recurrente_26" | "producto_26";
      pago_concepto: "frontend" | "mensual" | "upsell";
      sitio_estado_dns: "pendiente" | "apuntado" | "verificado";
      sitio_estatus:
        | "creado"
        | "build_ok"
        | "build_error"
        | "live"
        | "suspendido";
      suscripcion_estatus: "activa" | "pausada" | "cancelada";
      user_role: "operator" | "broker";
    };
    CompositeTypes: Record<string, never>;
  };
};

export type Tables<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Row"];
export type TablesInsert<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Insert"];
export type TablesUpdate<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Update"];
export type Enums<T extends keyof Database["public"]["Enums"]> =
  Database["public"]["Enums"][T];
